# Generated by Django 5.2.1 on 2025-05-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Body Part',
                'verbose_name_plural': 'Body Parts',
            },
        ),
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Difficulty Level',
                'verbose_name_plural': 'Difficulty Levels',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='EducationalMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='educational_materials/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video'), ('article', 'Article'), ('other', 'Other')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Educational Material',
                'verbose_name_plural': 'Educational Materials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='exercise_videos/')),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='exercise_thumbnails/')),
                ('instructions', models.TextField()),
                ('precautions', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True, help_text='If true, exercise is available to all doctors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Exercise Category',
                'verbose_name_plural': 'Exercise Categories',
            },
        ),
        migrations.CreateModel(
            name='ExerciseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='exercise_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Exercise Image',
                'verbose_name_plural': 'Exercise Images',
            },
        ),
    ]
