# Generated by Django 5.2.1 on 2025-05-30 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalmaterial',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercise',
            name='body_parts',
            field=models.ManyToManyField(related_name='exercises', to='exercises.bodypart'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exercises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercise',
            name='difficulty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercises.difficultylevel'),
        ),
        migrations.AddField(
            model_name='educationalmaterial',
            name='related_exercises',
            field=models.ManyToManyField(blank=True, related_name='educational_materials', to='exercises.exercise'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='categories',
            field=models.ManyToManyField(related_name='exercises', to='exercises.exercisecategory'),
        ),
        migrations.AddField(
            model_name='exerciseimage',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='exercises.exercise'),
        ),
    ]
