# Generated by Django 5.2.1 on 2025-06-15 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('instruction', models.TextField(help_text='Detailed instruction for this step')),
                ('image', models.ImageField(blank=True, help_text='Optional image for this step', null=True, upload_to='exercise_step_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='exercises.exercise')),
            ],
            options={
                'verbose_name': 'Exercise Step',
                'verbose_name_plural': 'Exercise Steps',
                'ordering': ['step_number'],
                'unique_together': {('exercise', 'step_number')},
            },
        ),
    ]
