# Generated by Django 5.2.1 on 2025-06-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_user_options_user_account_locked_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=150, verbose_name='По батькові'),
        ),
    ]
