# Generated by Django 5.2.1 on 2025-05-30 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Program Day',
                'verbose_name_plural': 'Program Days',
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='RehabilitationProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='draft', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rehabilitation Program',
                'verbose_name_plural': 'Rehabilitation Programs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField(default=1)),
                ('repetitions', models.PositiveIntegerField(default=1)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in seconds, if applicable', null=True)),
                ('rest_between_sets', models.PositiveIntegerField(default=60, help_text='Rest time in seconds')),
                ('order', models.PositiveIntegerField(default=0)),
                ('additional_instructions', models.TextField(blank=True, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
                ('program_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='programs.programday')),
            ],
            options={
                'verbose_name': 'Program Exercise',
                'verbose_name_plural': 'Program Exercises',
                'ordering': ['order'],
            },
        ),
    ]
