# Generated by Django 5.2.1 on 2025-05-30 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videoprocessingstatus',
            name='media_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing_status', to='media.mediafile'),
        ),
    ]
