# Generated by Django 5.2.1 on 2025-06-17 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
        ('progress', '0002_initial'),
        ('staff', '0004_alter_user_patronymic'),
    ]

    operations = [
        migrations.CreateModel(
            name='RehabilitationGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('mobility', 'Mobility'), ('strength', 'Strength'), ('flexibility', 'Flexibility'), ('balance', 'Balance'), ('pain', 'Pain Management'), ('cognitive', 'Cognitive Functions'), ('speech', 'Speech')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('current_value', models.FloatField(default=0, help_text='Current progress value')),
                ('target_value', models.FloatField(help_text='Target value to achieve')),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement (e.g., minutes, repetitions)', max_length=50)),
                ('target_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_achieved', models.BooleanField(default=False)),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_goals', to='staff.staffprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehabilitation_goals', to='patients.patientprofile')),
            ],
            options={
                'verbose_name': 'Rehabilitation Goal',
                'verbose_name_plural': 'Rehabilitation Goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staffprofile')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='progress.rehabilitationgoal')),
            ],
            options={
                'verbose_name': 'Goal Progress',
                'verbose_name_plural': 'Goal Progress Entries',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.DeleteModel(
            name='ProgressPhoto',
        ),
    ]
